=== BB-333/Community_Center/community_centre_website-login/xml/community_venues.dtd
<!ELEMENT venueListing (venue+)>
<!ATTLIST venueListing id CDATA "Community Centre Venues">
<!ELEMENT venue (name, street, suburb, state, postcode, description, facilityA, facilityB, facilityC, facilityD, facilityE)>
<!ATTLIST venue id (ArtsHouse|CommunityGym|CommunityLibrary) "CommunityLibrary">
<!ELEMENT name (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT suburb (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT facilityA (#PCDATA)>
<!ELEMENT facilityB (#PCDATA)>
<!ELEMENT facilityC (#PCDATA)>
<!ELEMENT facilityD (#PCDATA)>
<!ELEMENT facilityE (#PCDATA)>

=== BB-333/Community_Center/community_centre_website-login/xml/community_venues.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE venueListing SYSTEM "community_venues.dtd">

<venueListing id="Community Centre Venues">
    <venue id="ArtsHouse">
        <name>Arts House</name>
        <street>123 Main Street</street>
        <suburb>North City</suburb>
        <state>ABC</state>
        <postcode>1234</postcode>
        <description>Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.</description>
        <facilityA>Kitchen</facilityA>
        <facilityB>Bathrooms</facilityB>
        <facilityC>WIFI</facilityC>
        <facilityD>AV Equipment</facilityD>
        <facilityE>Seating</facilityE>
    </venue>
    <venue id="CommunityGym">
        <name>Community Gym</name>
        <street>123 High Street</street>
        <suburb>North City</suburb>
        <state>ABC</state>
        <postcode>1234</postcode>
        <description>Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.</description>
        <facilityA>Changerooms</facilityA>
        <facilityB>Bathrooms</facilityB>
        <facilityC>WIFI</facilityC>
        <facilityD>Kitchenette</facilityD>
        <facilityE>Lockers</facilityE>
    </venue>
    <venue id="CommunityLibrary">
        <name>Community Library</name>
        <street>234 High Street</street>
        <suburb>North City</suburb>
        <state>ABC</state>
        <postcode>1234</postcode>
        <description>Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.</description>
        <facilityA>Tables</facilityA>
        <facilityB>Bathrooms</facilityB>
        <facilityC>WIFI</facilityC>
        <facilityD>AV Equipment</facilityD>
        <facilityE>Seating</facilityE>
    </venue>
</venueListing>
